Moving list of approvers from .env to GitHub team
paritytech/substrate-tip-bot pull request #35
Opened 2022-12-12 18:17 UTC by mutantcornholio

Alongside the feature, following changes were made:
* Using `opstooling-integrations` for GitHub interations
* Upgraded `probot`, in order to align underlying `octokit` versions
between `opstooling-integrations` and `probot` itself
* Upgraded `opstooling-js` for the same reason

2022-12-12 21:11 UTC, mordamax commented on src/bot.ts
> +process.env.GITHUB_PRIVATE_KEY = process.env.PRIVATE_KEY;
Im curious - could it be that we will need several types of auth? how would setting env look like?
i felt several times during review of opstooling integrations and here that it'd maybe be ideal if auth won't be dependent of env vars, but on some other configuration. Either passed by parameters or some config class wrapper. 
Just leaving thoughts, not a request to an action

2022-12-12 21:13 UTC, mordamax approved these changes

2022-12-12 21:14 UTC, mordamax commented
probably missing the updates to helm?
like https://github.com/paritytech/substrate-tip-bot/blob/master/helm/values-parity-stg.yaml#L10

2022-12-12 21:15 UTC, mordamax requested changes
probably missing the updates to helm?
like https://github.com/paritytech/substrate-tip-bot/blob/master/helm/values-parity-stg.yaml#L10

2022-12-13 09:31 UTC, mutantcornholio commented
> probably missing the updates to helm?
like https://github.com/paritytech/substrate-tip-bot/blob/master/helm/values-parity-stg.yaml#L10

Yeah

2022-12-14 11:05 UTC, mutantcornholio commented
> probably missing the updates to helm? like https://github.com/paritytech/substrate-tip-bot/blob/master/helm/values-parity-stg.yaml#L10

I initially wanted to put it in secrets, but that info is by no means secret, so hardcoding it into the helm config seems viable

2022-12-19 17:58 UTC, merged